spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/ttms
      database: ttms
      
  output:
    ansi:
      enabled: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: yogeshmalathy29@gmail.com
    password: detwkimcysjimpox
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /ttms

springdoc:
  swagger-ui:
    path: /ui

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

com:
  custom:
    reset-link: http://localhost:5173/#/reset-password
    isSignUp: true
    swagger-path: /ttms/api/
    swagger-live-path: /ttms/api/